### ISSUE TITLE
Intermittent I get an error when opening/ saving makers in the admin screens

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#43]
admin.makeries.com

I clicked on one of the makers to go to the edit screen for that maker and this happened:

(its appears to be random, sometimes I can open a maker, make changes, then  save it but then go to open the same maker and get the exception; sometimes it happens the first time I go to open a maker)

string(3183) "GuzzleHttp\Exception\ConnectException: cURL error 28: Resolving timed out after 2511 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
Stack trace:
#0 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Client.php(361): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Client.php(163): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/www/html/makeries-v2/admin/vendor/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /var/www/html/makeries-v2/admin/classes/lib/my/ApiV2.php(85): GuzzleHttp\Client->request('GET', 'region', Array)
#14 /var/www/html/makeries-v2/admin/classes/lib/my/ApiV2.php(31): ApiV2->request('GET', 'region', Array)
#15 /var/www/html/makeries-v2/admin/classes/app/backend/modules/maker/actions/actions.class.php(80): ApiV2->get('region')
#16 /var/www/html/makeries-v2/admin/classes/lib/core/Router.php(183): makerActions->executeEdit()
#17 /var/www/html/makeries-v2/admin/web/backend/index.php(106): Router->dispatch(Array)
#18 {main}message"

**Comment by macep** [comment]
I'm closing this issue for the time being and will reopen when I can reproduce it consistently
